<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Signature certificate — {{ $documentLabel }}</title>
    <style>
        body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 30px; color: #1e293b; background: #ffffff; font-size: 12px; line-height: 1.5; }
        .container { max-width: 720px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 2px solid #0f172a; padding-bottom: 16px; margin-bottom: 24px; }
        .club-name { font-size: 20px; font-weight: 900; color: #0f172a; text-transform: uppercase; }
        .report-title { font-size: 14px; font-weight: 700; color: #334155; margin-top: 4px; }
        .status-badge { display: inline-block; margin-top: 8px; padding: 3px 10px; border-radius: 9999px; font-size: 10px; font-weight: 800; text-transform: uppercase; background: #dcfce7; color: #15803d; border: 1px solid #bbf7d0; }
        .section-title { font-size: 13px; font-weight: 900; text-transform: uppercase; color: #0f172a; margin-top: 24px; margin-bottom: 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
        td { padding: 5px 0; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
        td.label { width: 160px; color: #64748b; font-size: 10px; text-transform: uppercase; font-weight: 700; }
        .signature-box { margin-top: 16px; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; text-align: center; background: #f8fafc; }
        .signature-typed { font-family: 'DejaVu Sans', cursive; font-style: italic; font-size: 34px; color: #0f172a; }
        .signature-drawn img { max-height: 100px; max-width: 100%; }
        .muted { color: #64748b; font-size: 10px; }
        .footer { margin-top: 32px; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #f1f5f9; padding-top: 16px; }
        .hash { font-family: monospace; word-break: break-all; }
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <div class="club-name">{{ $club->name }}</div>
        <div class="report-title">{{ $documentLabel }}</div>
        <span class="status-badge">Signed</span>
    </div>

    <div class="section-title">Signature</div>
    <div class="signature-box">
        @if($request->method === 'typed')
            <div class="signature-typed">{{ $request->typed_name }}</div>
        @elseif($signatureImage)
            <div class="signature-drawn"><img src="{{ $signatureImage }}" alt="Signature"></div>
        @endif
    </div>

    <div class="section-title">Details</div>
    <table>
        <tr><td class="label">Signed by</td><td>{{ $request->signer_name }}{{ $request->signer_email ? ' ('.$request->signer_email.')' : '' }}</td></tr>
        <tr><td class="label">Method</td><td>{{ $request->method === 'typed' ? 'Typed name' : 'Drawn signature' }}</td></tr>
        <tr><td class="label">Signed on</td><td>{{ $request->signed_at?->format('j F Y, H:i') }}</td></tr>
        <tr><td class="label">Requested by</td><td>{{ $request->requestedBy?->name ?? '—' }} on {{ $request->requested_at?->format('j F Y') }}</td></tr>
        <tr><td class="label">IP address</td><td>{{ $request->consent_ip }}</td></tr>
        <tr><td class="label">Consent</td><td>The signer confirmed this was their electronic signature, intended to have the same effect as a handwritten signature.</td></tr>
        <tr><td class="label">Document reference</td><td class="hash">{{ $request->document_hash }}</td></tr>
    </table>

    <div class="footer">
        This certificate is generated by Club Manager as a record of an electronic signature. It is not itself the document that was signed, but confirms who signed it, how, and when.
    </div>
</div>
</body>
</html>
