// The website builder's colour themes: one definition used by the editor's live preview and by the real
// public site (Public/Site.vue), so a theme only has to be written once and the preview can never drift
// from what a visitor actually sees.

export const SITE_THEME_IDS = [
    'classic', 'obsidian', 'masonic', 'minimal', 'vibrant',
    'light_navy', 'executive_light', 'masonic_light', 'warm_light',
];

// The gallery shown on the Themes tab: name, description and a swatch preview for each theme.
export const SITE_THEMES = [
    {
        id: 'light_navy',
        name: 'Pure White & Oxford Navy',
        badge: 'White Canvas / Navy',
        isLight: true,
        description: 'Pristine pure white background with Oxford Navy typography, crisp card borders, and subtle sky blue accents.',
        previewBg: 'bg-gradient-to-br from-white via-slate-50 to-slate-100 border border-slate-200 dark:border-slate-800 shadow-inner',
        palette: ['#ffffff', '#0f172a', '#0284c7', '#38bdf8'],
        features: ['100% White background', 'Oxford Navy typography', 'Crisp card borders', 'Clean corporate header'],
    },
    {
        id: 'executive_light',
        name: 'Executive Slate & Indigo',
        badge: 'Executive Light',
        isLight: true,
        description: 'Off-white light background with elevated white cards, deep slate headings, and royal indigo highlights.',
        previewBg: 'bg-gradient-to-br from-slate-100 via-blue-50/50 dark:via-blue-950/50 to-slate-200 border border-slate-200 dark:border-slate-800 shadow-inner',
        palette: ['#f8fafc', '#1e1b4b', '#4f46e5', '#6366f1'],
        features: ['Soft off-white background', 'Indigo accent bar', 'Elevated white cards', 'Modern floating header'],
    },
    {
        id: 'masonic_light',
        name: 'White Gold Masonic Lodge',
        badge: 'White & Royal Gold',
        isLight: true,
        description: 'Traditional fraternal lodge layout set on a pure white background with gold foil borders and dark navy serif typography.',
        previewBg: 'bg-gradient-to-br from-white via-amber-50/30 dark:via-amber-950/30 to-slate-100 border border-amber-300 dark:border-amber-700/60 shadow-inner',
        palette: ['#ffffff', '#0c1938', '#d97706', '#fbbf24'],
        features: ['Pure white background', 'Gold foil card borders', 'Dark navy serif typography', 'Regal gold badges'],
    },
    {
        id: 'minimal',
        name: 'Minimalist Emerald Light',
        badge: 'Clean & Flat Light',
        isLight: true,
        description: 'Bright, airy, contemporary design with generous whitespace, crisp emerald green accents, high-contrast typography, and flat white cards.',
        previewBg: 'bg-gradient-to-br from-white via-emerald-50/30 dark:via-emerald-950/30 to-slate-100 border border-emerald-200 dark:border-emerald-800/60 shadow-inner',
        palette: ['#ffffff', '#059669', '#10b981', '#1e293b'],
        features: ['Airy whitespace layout', 'Emerald green highlights', 'Flat modern borders', 'High-contrast typography'],
    },
    {
        id: 'warm_light',
        name: 'Warm Cream & Bronze',
        badge: 'Warm Light',
        isLight: true,
        description: 'Soft warm ivory background with rich bronze accents, rounded white cards, and inviting warm tones.',
        previewBg: 'bg-gradient-to-br from-amber-50/50 dark:from-amber-950/50 via-orange-50/30 dark:via-orange-950/30 to-amber-100/50 dark:to-amber-900/50 border border-amber-200 dark:border-amber-800/60 shadow-inner',
        palette: ['#fffbe6', '#78350f', '#b45309', '#f59e0b'],
        features: ['Warm ivory backdrop', 'Bronze & Amber accents', 'Rounded white cards', 'Inviting layout'],
    },
    {
        id: 'classic',
        name: 'Classic Dark Heritage',
        badge: 'Classic Dark',
        isLight: false,
        description: 'Clean, timeless corporate and club layout featuring crisp white cards on dark slate, rich navy accents, gold highlights, and subtle shadows.',
        previewBg: 'bg-gradient-to-br from-slate-900 via-blue-900 to-blue-950 shadow-inner',
        palette: ['#0f172a', '#0284c7', '#d97706', '#f8fafc'],
        features: ['Navy & Amber accents', 'Classic serif headings', 'Subtle card elevations', 'Centered footer navigation'],
    },
    {
        id: 'obsidian',
        name: 'Obsidian Dark',
        badge: 'Modern Dark Mode',
        isLight: false,
        description: 'Sleek, high-tech dark mode aesthetic with midnight background, glassmorphism panel surfaces, and glowing cyan/indigo accents.',
        previewBg: 'bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 shadow-inner',
        palette: ['#020617', '#38bdf8', '#818cf8', '#1e293b'],
        features: ['Midnight dark backdrop', 'Glassmorphism panels', 'Neon accent glows', 'Compact dark header bar'],
    },
    {
        id: 'masonic',
        name: 'Royal Masonic Dark & Gold',
        badge: 'Regal Dark',
        isLight: false,
        description: 'Traditional Masonic & fraternal lodge aesthetic featuring deep royal navy, rich gold foil borders, crest embellishments, and classic serif typography.',
        previewBg: 'bg-gradient-to-br from-blue-950 via-slate-950 to-blue-950 shadow-inner',
        palette: ['#0c1938', '#f59e0b', '#d97706', '#1e1b4b'],
        features: ['Royal Navy & Gold palette', 'Lodge crest detailing', 'Regal badge styling', 'Ornate section dividers'],
    },
    {
        id: 'vibrant',
        name: 'Vibrant Sunset Dark',
        badge: 'High Impact Banners',
        isLight: false,
        description: 'Dynamic, high-energy theme with bold gradient hero banners, warm coral and amber tones, rounded cards, and prominent action buttons.',
        previewBg: 'bg-gradient-to-br from-amber-900 via-rose-950 to-blue-950 shadow-inner',
        palette: ['#f43f5e', '#fb923c', '#4c1d95', '#fff1f2'],
        features: ['Sunset gradient headers', 'Warm coral & amber tones', 'Rounded card borders', 'Prominent action CTAs'],
    },
];

/**
 * The Tailwind classes for one theme. `wrapper`/`header` are used by the public site's outer shell;
 * `container`/`nav` are aliases of the same classes for the editor's boxed-in preview mockup.
 */
export function themeClasses(key) {
    const base = THEME_CLASS_TABLE[key] || THEME_CLASS_TABLE.classic;

    return {
        ...base,
        container: base.wrapper,
        nav: base.header,
    };
}

const THEME_CLASS_TABLE = {
    light_navy: {
        wrapper: 'bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-sans selection:bg-blue-500 selection:text-white',
        header: 'sticky top-0 z-50 bg-white/95 dark:bg-slate-900/95 backdrop-blur-md border-b border-slate-200/90 dark:border-slate-800/90 shadow-sm',
        navActive: 'bg-slate-900 dark:bg-slate-700 text-white font-bold shadow-md shadow-slate-900/10',
        navInactive: 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white border-transparent',
        heroBg: 'bg-gradient-to-br from-slate-900 via-slate-800 to-blue-950 text-white border border-slate-800 shadow-xl',
        heroPill: 'bg-blue-500/20 border-blue-400/30 text-blue-300 font-semibold',
        heroCta: 'bg-blue-600 hover:bg-blue-700 text-white font-bold shadow-blue-600/25',
        cardBg: 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white shadow-sm hover:shadow-md transition-shadow',
        headingText: 'text-slate-900 dark:text-white',
        bodyText: 'text-slate-700 dark:text-slate-200',
        accentText: 'text-blue-600 dark:text-blue-400',
        accentBg: 'bg-blue-600',
        footer: 'bg-slate-900 dark:bg-slate-700 border-t border-slate-800 text-slate-400',
    },
    executive_light: {
        wrapper: 'bg-slate-50 dark:bg-slate-800/50 text-slate-900 dark:text-white font-sans selection:bg-blue-600 selection:text-white',
        header: 'sticky top-0 z-50 bg-white/90 dark:bg-slate-900/90 backdrop-blur-md border-b border-slate-200/80 dark:border-slate-800/80 shadow-sm',
        navActive: 'bg-blue-50 dark:bg-blue-950/40 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-800/60 font-bold shadow-sm',
        navInactive: 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white border-transparent',
        heroBg: 'bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800/90 shadow-md text-slate-900 dark:text-white',
        heroPill: 'bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-800/60 text-blue-700 dark:text-blue-300 font-semibold',
        heroCta: 'bg-gradient-to-r from-blue-600 to-blue-600 text-white font-bold shadow-blue-600/20',
        cardBg: 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white shadow-sm hover:border-blue-200 dark:hover:border-blue-800/60 transition-colors',
        headingText: 'text-slate-900 dark:text-white',
        bodyText: 'text-slate-700 dark:text-slate-200',
        accentText: 'text-blue-600 dark:text-blue-400',
        accentBg: 'bg-blue-600',
        footer: 'bg-white dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-300',
    },
    masonic_light: {
        wrapper: 'bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-serif selection:bg-amber-500 selection:text-slate-950 dark:selection:text-white',
        header: 'sticky top-0 z-50 bg-white/95 dark:bg-slate-900/95 backdrop-blur-md border-b-2 border-amber-500/40 shadow-sm',
        navActive: 'bg-amber-50 dark:bg-amber-950/40 text-amber-900 dark:text-amber-200 border-amber-300 dark:border-amber-700/60 font-sans font-bold shadow-sm',
        navInactive: 'text-slate-700 dark:text-slate-200 hover:text-amber-800 dark:hover:text-amber-200 font-sans border-transparent',
        heroBg: 'bg-gradient-to-br from-blue-950 via-blue-950 to-slate-950 text-white border-2 border-amber-500/40 shadow-xl',
        heroPill: 'bg-amber-500/20 border-amber-400/40 text-amber-300 font-sans tracking-widest',
        heroCta: 'bg-gradient-to-r from-amber-500 to-amber-600 text-slate-950 dark:text-white font-sans font-black shadow-amber-500/30',
        cardBg: 'bg-white dark:bg-slate-900 border border-amber-500/30 text-slate-900 dark:text-white shadow-sm hover:border-amber-500/50 transition-colors',
        headingText: 'text-slate-900 dark:text-white',
        bodyText: 'text-slate-700 dark:text-slate-200',
        accentText: 'text-amber-700 dark:text-amber-300',
        accentBg: 'bg-amber-600',
        footer: 'bg-slate-900 dark:bg-slate-700 border-t-2 border-amber-500/40 text-slate-400 font-sans',
    },
    warm_light: {
        wrapper: 'bg-amber-50/30 dark:bg-amber-950/30 text-slate-900 dark:text-white font-sans selection:bg-amber-500 selection:text-white',
        header: 'sticky top-0 z-50 bg-white/95 dark:bg-slate-900/95 backdrop-blur-md border-b border-amber-200/60 dark:border-amber-800/60 shadow-sm',
        navActive: 'bg-amber-100/70 dark:bg-amber-900/70 text-amber-900 dark:text-amber-200 border-amber-300 dark:border-amber-700/60 font-bold',
        navInactive: 'text-slate-600 dark:text-slate-300 hover:text-amber-900 dark:hover:text-amber-200 border-transparent',
        heroBg: 'bg-gradient-to-br from-amber-900 via-amber-950 to-orange-950 text-amber-50 border border-amber-700/50 shadow-xl',
        heroPill: 'bg-amber-500/20 border-amber-400/40 text-amber-300',
        heroCta: 'bg-gradient-to-r from-amber-500 to-amber-600 text-amber-950 dark:text-amber-100 font-bold',
        cardBg: 'bg-white dark:bg-slate-900 border border-amber-200 dark:border-amber-800/60 text-slate-900 dark:text-white shadow-sm hover:border-amber-300 dark:hover:border-amber-700/60 transition-colors',
        headingText: 'text-slate-900 dark:text-white',
        bodyText: 'text-slate-700 dark:text-slate-200',
        accentText: 'text-amber-700 dark:text-amber-300',
        accentBg: 'bg-amber-600',
        footer: 'bg-white dark:bg-slate-900 border-t border-amber-200/60 dark:border-amber-800/60 text-slate-600 dark:text-slate-300',
    },
    obsidian: {
        wrapper: 'bg-slate-950 text-slate-100 font-sans selection:bg-blue-500 selection:text-white',
        header: 'sticky top-0 z-50 backdrop-blur-xl bg-slate-950/90 border-b border-slate-800',
        navActive: 'bg-blue-500/20 text-blue-400 border-blue-500/40 shadow-sm shadow-blue-500/10',
        navInactive: 'text-slate-400 hover:text-white border-transparent',
        heroBg: 'bg-gradient-to-r from-slate-950 via-slate-900 to-slate-950 border border-slate-800/80 shadow-2xl',
        heroPill: 'bg-blue-500/10 border-blue-500/30 text-blue-400',
        heroCta: 'bg-gradient-to-r from-blue-500 to-blue-600 text-white shadow-blue-500/30',
        cardBg: 'bg-slate-900/90 border border-slate-800 text-slate-100 shadow-xl',
        headingText: 'text-white',
        bodyText: 'text-slate-300',
        accentText: 'text-blue-400',
        accentBg: 'bg-blue-500',
        footer: 'bg-slate-950 border-t border-slate-900 text-slate-500',
    },
    masonic: {
        wrapper: 'bg-slate-950 text-slate-100 font-serif selection:bg-amber-500 selection:text-slate-950',
        header: 'sticky top-0 z-50 backdrop-blur-xl bg-blue-950/90 border-b border-amber-500/30 shadow-md',
        navActive: 'bg-amber-500/20 text-amber-300 border-amber-500/50 shadow-sm',
        navInactive: 'text-slate-300 hover:text-amber-300 border-transparent',
        heroBg: 'bg-gradient-to-br from-blue-950 via-slate-950 to-blue-950 border-2 border-amber-500/30 shadow-2xl',
        heroPill: 'bg-amber-500/10 border-amber-500/30 text-amber-400 font-sans tracking-widest',
        heroCta: 'bg-gradient-to-r from-amber-600 to-amber-500 text-slate-950 dark:text-white font-black shadow-amber-500/20',
        cardBg: 'bg-blue-950/60 border border-amber-500/25 text-slate-100 shadow-xl',
        headingText: 'text-amber-100',
        bodyText: 'text-slate-300',
        accentText: 'text-amber-400',
        accentBg: 'bg-amber-500',
        footer: 'bg-blue-950 border-t border-amber-500/20 text-slate-400 font-sans',
    },
    minimal: {
        wrapper: 'bg-slate-50 dark:bg-slate-800/50 text-slate-900 dark:text-white font-sans selection:bg-emerald-500 selection:text-white',
        header: 'sticky top-0 z-50 bg-white/90 dark:bg-slate-900/90 backdrop-blur-md border-b border-slate-200 dark:border-slate-800 shadow-sm',
        navActive: 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300 border-emerald-300 dark:border-emerald-700/60 font-bold',
        navInactive: 'text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white border-transparent',
        heroBg: 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm text-slate-900 dark:text-white',
        heroPill: 'bg-emerald-50 dark:bg-emerald-950/40 border-emerald-200 dark:border-emerald-800/60 text-emerald-700 dark:text-emerald-300',
        heroCta: 'bg-emerald-700 hover:bg-emerald-800 text-white shadow-emerald-700/20',
        cardBg: 'bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-white shadow-sm',
        headingText: 'text-slate-900 dark:text-white',
        bodyText: 'text-slate-700 dark:text-slate-200',
        accentText: 'text-emerald-700 dark:text-emerald-400',
        accentBg: 'bg-emerald-600',
        footer: 'bg-white dark:bg-slate-900 border-t border-slate-200 dark:border-slate-800 text-slate-600 dark:text-slate-300',
    },
    vibrant: {
        wrapper: 'bg-slate-900 dark:bg-slate-700 text-slate-100 font-sans selection:bg-rose-500 selection:text-white',
        header: 'sticky top-0 z-50 backdrop-blur-xl bg-slate-900/90 border-b border-rose-500/20',
        navActive: 'bg-rose-500/20 text-rose-300 border-rose-500/40 shadow-sm',
        navInactive: 'text-slate-300 hover:text-rose-300 border-transparent',
        heroBg: 'bg-gradient-to-r from-rose-900 via-amber-900 to-blue-950 border border-rose-500/30 shadow-2xl',
        heroPill: 'bg-rose-500/20 border-rose-500/40 text-rose-300',
        heroCta: 'bg-gradient-to-r from-rose-500 via-amber-500 to-rose-600 text-white shadow-rose-500/30',
        cardBg: 'bg-slate-950/80 border border-slate-800 text-slate-100 shadow-xl',
        headingText: 'text-white',
        bodyText: 'text-slate-300',
        accentText: 'text-rose-400',
        accentBg: 'bg-rose-500',
        footer: 'bg-slate-950 border-t border-slate-800 text-slate-400',
    },
    classic: {
        wrapper: 'bg-slate-950 text-slate-100 font-sans selection:bg-blue-500 selection:text-white',
        header: 'sticky top-0 z-50 backdrop-blur-xl bg-slate-950/85 border-b border-slate-800',
        navActive: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
        navInactive: 'text-slate-400 hover:text-white border-transparent',
        heroBg: 'bg-gradient-to-r from-slate-900 via-blue-950/40 to-slate-900 border border-slate-800',
        heroPill: 'bg-blue-500/10 border-blue-500/20 text-blue-400',
        heroCta: 'bg-gradient-to-r from-blue-500 to-blue-600 text-white shadow-blue-500/20',
        cardBg: 'bg-slate-900 dark:bg-slate-700 border border-slate-800 text-slate-100 shadow-xl',
        headingText: 'text-white',
        bodyText: 'text-slate-300',
        accentText: 'text-blue-400',
        accentBg: 'bg-blue-500',
        footer: 'bg-slate-950 border-t border-slate-800 text-slate-400',
    },
};
